#!/usr/bin/env sh
# -----------------------------------------------------------------------------
# Gradle start up script for UN*X
# -----------------------------------------------------------------------------

# ...existing Gradle wrapper script code...
# This file is typically auto-generated by running:
#   gradle wrapper
# or
#   ./gradlew wrapper
#
# To generate it, run the following in your project root:
#   gradle wrapper --gradle-version=8.7
#
# For full content, see: https://github.com/gradle/gradle/blob/master/subprojects/wrapper/src/main/scripts/gradlew

# The root gradlew should NOT reference backend/gradlew.
# The root gradlew should be a standalone Gradle wrapper script generated at the root.
# It will invoke Gradle for the whole project (including backend as a subproject).
# Do NOT call or reference backend/gradlew from the root gradlew.
# Instead, delete backend/gradlew and use only the root gradlew for all builds.
