@echo off
REM -----------------------------------------------------------------------------
REM Gradle start up script for Windows
REM -----------------------------------------------------------------------------

REM ...existing Gradle wrapper script code...
REM This file is typically auto-generated by running:
REM   gradle wrapper
REM or
REM   .\gradlew wrapper
REM
REM To generate it, run the following in your project root:
REM   gradle wrapper --gradle-version=8.7
REM
REM For full content, see: https://github.com/gradle/gradle/blob/master/subprojects/wrapper/src/main/scripts/gradlew.bat
